# -*- coding: utf-8 -*-
"""Copy_of_Copy_of_Neural_Receiver_IEEE80211p.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JMn7L5z9YyssFfh1BsYWy0rAgCMBDa2N
"""

# Import Sionna
# try:
#     import sionna
# except ImportError as e:
#     # Install Sionna if package is not already installed
#     import os
#     os.system("pip install sionna")
#     import sionna

# import sionna
import os 
import sys
sys.path.insert(0, os.getcwd()+'/...') # +'/..'
sys.path.insert(0, os.getcwd()+'/..') # +'/..'
sys.path.insert(0, os.getcwd()+'/') # +'/..'

import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')
print('Number of GPUs available :', len(gpus))
if gpus:
    gpu_num = 0 # Index of the GPU to use
    try:
        tf.config.set_visible_devices(gpus[gpu_num], 'GPU')
        print('Only GPU number', gpu_num, 'used.')
        tf.config.experimental.set_memory_growth(gpus[gpu_num], True)
    except RuntimeError as e:
        print(e)


# get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib.pyplot as plt
import numpy as np
import pickle

from tensorflow.keras import Model
from tensorflow.keras.layers import Layer, Conv2D, LayerNormalization
from tensorflow.nn import relu

from sionna.mapping import Constellation
from sionna.channel.tr38901 import Antenna, AntennaArray, CDL
from sionna.channel import OFDMChannel
from sionna.mimo import StreamManagement
from sionna.ofdm import ResourceGrid, ResourceGridMapper, LSChannelEstimator, LMMSEEqualizer, RemoveNulledSubcarriers, ResourceGridDemapper
from sionna.utils import BinarySource, ebnodb2no, insert_dims, flatten_last_dims, log10, expand_to_rank
from sionna.fec.ldpc.encoding import LDPC5GEncoder
from sionna.fec.ldpc.decoding import LDPC5GDecoder
from sionna.fec.conv import ConvEncoder, ViterbiDecoder
from sionna.mapping import Mapper, Demapper
from sionna.utils.metrics import compute_ber
from sionna.utils import sim_ber
from sionna.ofdm import PilotPattern, RemoveNulledSubcarriers


# from IEEE80211helper import generate_ieee8211_constellation
# from IEEE80211helper import IEEE80211Scrambler, IEEE80211Interleaver

# In[16]:


import math
import itertools

"""# 1. IEEE 802.11helper.py file"""

# IEEE 802.11helper.py file

# import numpy as np
# import tensorflow as tf



# from tensorflow.keras.layers import Layer



def generate_ieee8211_constellation(mu = 1, normalize = True, show_constellation = False):
    assert mu in (1,2,4,6),\
    "currently ony supports mu  = 1, 2, 4, and 6"
    if mu == 1:
        mapping_table = {
        (0,) : -1.+0.j,
        (1,) :  1.+0.j
        }
    elif mu == 2:
        mapping_table = {
            (0,0) : -1.-1.j,
            (0,1) : -1.+1.j,
            (1,0) :  1.-1.j,
            (1,1) :  1.+1.j
        }
    elif mu == 4:
        mapping_table = {
            (0,0,0,0) : -3.-3.j,
            (0,0,0,1) : -3.-1.j,
            (0,0,1,0) : -3.+3.j,
            (0,0,1,1) : -3.+1.j,
            (0,1,0,0) : -1.-3.j,
            (0,1,0,1) : -1.-1.j,
            (0,1,1,0) : -1.+3.j,
            (0,1,1,1) : -1.+1.j,
            (1,0,0,0) :  3.-3.j,
            (1,0,0,1) :  3.-1.j,
            (1,0,1,0) :  3.+3.j,
            (1,0,1,1) :  3.+1.j,
            (1,1,0,0) :  1.-3.j,
            (1,1,0,1) :  1.-1.j,
            (1,1,1,0) :  1.+3.j,
            (1,1,1,1) :  1.+1.j
        }
    elif mu == 6:
        mapping_table = {
            (0,0,0,0,0,0)   :  -7.-7.j, 
            (0,0,0,0,0,1)   :  -7.-5.j, 
            (0,0,0,0,1,0)   :  -7.-1.j, 
            (0,0,0,0,1,1)   :  -7.-3.j, 
            (0,0,0,1,0,0)   :  -7.+7.j, 
            (0,0,0,1,0,1)   :  -7.+5.j, 
            (0,0,0,1,1,0)   :  -7.+1.j, 
            (0,0,0,1,1,1)   :  -7.+3.j, 
            (0,0,1,0,0,0)   :  -5.-7.j, 
            (0,0,1,0,0,1)   :  -5.-5.j, 
            (0,0,1,0,1,0)   :  -5.-1.j, 
            (0,0,1,0,1,1)   :  -5.-3.j, 
            (0,0,1,1,0,0)   :  -5.+7.j, 
            (0,0,1,1,0,1)   :  -5.+5.j, 
            (0,0,1,1,1,0)   :  -5.+1.j, 
            (0,0,1,1,1,1)   :  -5.+3.j, 
            (0,1,0,0,0,0)   :  -1.-7.j, 
            (0,1,0,0,0,1)   :  -1.-5.j, 
            (0,1,0,0,1,0)   :  -1.-1.j, 
            (0,1,0,0,1,1)   :  -1.-3.j, 
            (0,1,0,1,0,0)   :  -1.+7.j, 
            (0,1,0,1,0,1)   :  -1.+5.j, 
            (0,1,0,1,1,0)   :  -1.+1.j, 
            (0,1,0,1,1,1)   :  -1.+3.j, 
            (0,1,1,0,0,0)   :  -3.-7.j, 
            (0,1,1,0,0,1)   :  -3.-5.j, 
            (0,1,1,0,1,0)   :  -3.-1.j, 
            (0,1,1,0,1,1)   :  -3.-3.j, 
            (0,1,1,1,0,0)   :  -3.+7.j, 
            (0,1,1,1,0,1)   :  -3.+5.j, 
            (0,1,1,1,1,0)   :  -3.+1.j, 
            (0,1,1,1,1,1)   :  -3.+3.j, 
            (1,0,0,0,0,0)   :   7.-7.j, 
            (1,0,0,0,0,1)   :   7.-5.j, 
            (1,0,0,0,1,0)   :   7.-1.j, 
            (1,0,0,0,1,1)   :   7.-3.j, 
            (1,0,0,1,0,0)   :   7.+7.j, 
            (1,0,0,1,0,1)   :   7.+5.j, 
            (1,0,0,1,1,0)   :   7.+1.j, 
            (1,0,0,1,1,1)   :   7.+3.j, 
            (1,0,1,0,0,0)   :   5.-7.j, 
            (1,0,1,0,0,1)   :   5.-5.j, 
            (1,0,1,0,1,0)   :   5.-1.j, 
            (1,0,1,0,1,1)   :   5.-3.j, 
            (1,0,1,1,0,0)   :   5.+7.j, 
            (1,0,1,1,0,1)   :   5.+5.j, 
            (1,0,1,1,1,0)   :   5.+1.j, 
            (1,0,1,1,1,1)   :   5.+3.j, 
            (1,1,0,0,0,0)   :   1.-7.j, 
            (1,1,0,0,0,1)   :   1.-5.j, 
            (1,1,0,0,1,0)   :   1.-1.j, 
            (1,1,0,0,1,1)   :   1.-3.j, 
            (1,1,0,1,0,0)   :   1.+7.j, 
            (1,1,0,1,0,1)   :   1.+5.j, 
            (1,1,0,1,1,0)   :   1.+1.j, 
            (1,1,0,1,1,1)   :   1.+3.j, 
            (1,1,1,0,0,0)   :   3.-7.j, 
            (1,1,1,0,0,1)   :   3.-5.j, 
            (1,1,1,0,1,0)   :   3.-1.j, 
            (1,1,1,0,1,1)   :   3.-3.j, 
            (1,1,1,1,0,0)   :   3.+7.j, 
            (1,1,1,1,0,1)   :   3.+5.j, 
            (1,1,1,1,1,0)   :   3.+1.j, 
            (1,1,1,1,1,1)   :   3.+3.j
        }
    else:
        mapping_table = None
        
    initial_value = np.array(list(mapping_table.values()),
                            dtype= complex)
    constellation = Constellation("custom", num_bits_per_symbol = mu, initial_value=initial_value,
                normalize=normalize, center=False, trainable=True)
    if show_constellation:
        constellation.show(figsize=(10, 10))
    return constellation

    

class IEEE80211Scrambler(Layer):
    
    def __init__(self, seed = 127, binary = True, dtype  = tf.float32, batch_size = 64, **kwargs ):
        
        self._binary  = binary
        self._batch_size = batch_size
        if seed is not None:
            self.seed  = seed
        else:
            self.seed   = 127
        
        self.sequence = None
        
        super().__init__(dtype=dtype, **kwargs)

    def _de2bi(self, n, N):
        bseed= bin(n).replace("0b", "")
        fix = N-len(bseed)
        pad = np.zeros(fix)
        pad = pad.tolist()
        y = []
        for i in range(len(pad)):
            y = [int(pad[i])] + y
        for i in range(len(bseed)):
            y = [int(bseed[i])] + y
        return y
            
    def _generate_scrambling(self, len_input_shape):
        
        bit_count =len_input_shape # len(bits)
        
        N=7
        bseed = self._de2bi(self.seed, N)
        bseed = np.array(bseed, dtype=int)
        x = np.zeros((N,), dtype = int)
        x = bseed
        var_arr = np.zeros(bit_count, dtype = int)
        
        
        for n in range(bit_count):
            var = int(x[3])^int(x[6])
            x[1:] = x[0:6]
            x[0] = var
            var_arr[n] = var
        
        self.sequence = tf.convert_to_tensor(var_arr, dtype = tf.int32)          
            
    def build(self, input_shape):
        """Build the model and initialize variables."""
        # self.input_shape = input_shape
        pass
    
    def call(self, inputs):
        is_binary = self._binary # can be overwritten if explicitly provided

        if isinstance(inputs, (tuple, list)):
            if len(inputs)==1: # if user wants to call with call([x])
                seed = None
                x = inputs
            elif len(inputs)==2:
                x, seed = inputs
            elif len(inputs)==3:
            # allow that flag binary is explicitly provided (for descrambler)
                x, seed, is_binary = inputs
                # is binary can be either a tensor or bool
                if isinstance(is_binary, tf.Tensor):
                    if not is_binary.dtype.is_bool:
                        raise TypeError("binary must be bool.")
                else: # is boolean
                    assert isinstance(is_binary.dtype, bool), \
                    "binary must be bool."
            else:
                raise TypeError("inputs cannot have more than 3 entries.")
        else:
            seed = self.seed
            x = inputs
        
        self.len_input_shape = len(x[0,0,0])
        self.seed = seed
        self._generate_scrambling( self.len_input_shape)
        
        self.sequence = tf.tile(tf.expand_dims(tf.expand_dims(tf.expand_dims(self.sequence,axis  = 0),0),0),
                                [self._batch_size,1,1,1]) # TODO remove hardcoded batch size

        # scrambled_bits = tf.zeros(x.shape[0], dtype = tf.int32)
        scrambled_bits = tf.bitwise.bitwise_xor(tf.cast(x, self.sequence.dtype),self.sequence)
                                                
        
        return tf.cast(scrambled_bits, x.dtype)


class IEEE80211Interleaver(Layer):
    
    def __init__(self,
                NCBPS,
                axis=-1,
                inverse=False,
                dtype=tf.float32,
                **kwargs):
        
        self.NCBPS = NCBPS
        self._inverse = inverse
        self._axis = axis
        
        super().__init__(dtype=dtype, **kwargs)
    
    def _generate_perm(self):
        assert self.NCBPS in (48,96,192,288),\
        "currently ony supports NCBPS  = 48,96,192, and 288"
        if self.NCBPS == 48:
            w48 = [1, 17, 33, 2, 18, 34, 3, 19, 35, 4, 20, 36, 5, 21, 37, 6, 22, 38, 7, 23, 39, 8, 24, 40, 9, 25, 41, 10, 26, 42, 11, 27, 43, 12, 28, 44, 13, 29, 45, 14, 30, 46, 15, 31, 47, 16, 32, 48]
            k48 = [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]
            p =  [(w48[j]-1) for j in range(0, 48)]
            pinv =  [(k48[j]-1) for j in range(0, 48)]
        elif self.NCBPS == 96:
            w96 = [1, 17, 33, 49, 65, 81, 2, 18, 34, 50, 66, 82, 3, 19, 35, 51, 67, 83, 4, 20, 36, 52, 68, 84, 5, 21, 37, 53, 69, 85, 6, 22, 38, 54, 70, 86, 7, 23, 39, 55, 71, 87, 8, 24, 40, 56, 72, 88, 9, 25, 41, 57, 73, 89, 10, 26, 42, 58, 74, 90, 11, 27, 43, 59, 75, 91, 12, 28, 44, 60, 76, 92, 13, 29, 45, 61, 77, 93, 14, 30, 46, 62, 78, 94, 15, 31, 47, 63, 79, 95, 16, 32, 48, 64, 80, 96]
            k96 = [1, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 2, 8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 4, 10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94, 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89, 95, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96] 
            p = [(w96[j]-1) for j in range(0, 96)]
            pinv = [(k96[j]-1) for j in range(0, 96)]
        elif self.NCBPS == 192:
            w192 = [1, 17, 33, 49, 65, 81, 97, 113, 129, 145, 161, 177, 18, 2, 50, 34, 82, 66, 114, 98, 146, 130, 178, 162, 3, 19, 35, 51, 67, 83, 99, 115, 131, 147, 163, 179, 20, 4, 52, 36, 84, 68, 116, 100, 148, 132, 180, 164, 5, 21, 37, 53, 69, 85, 101, 117, 133, 149, 165, 181, 22, 6, 54, 38, 86, 70, 118, 102, 150, 134, 182, 166, 7, 23, 39, 55, 71, 87, 103, 119, 135, 151, 167, 183, 24, 8, 56, 40, 88, 72, 120, 104, 152, 136, 184, 168, 9, 25, 41, 57, 73, 89, 105, 121, 137, 153, 169, 185, 26, 10, 58, 42, 90, 74, 122, 106, 154, 138, 186, 170, 11, 27, 43, 59, 75, 91, 107, 123, 139, 155, 171, 187, 28, 12, 60, 44, 92, 76, 124, 108, 156, 140, 188, 172, 13, 29, 45, 61, 77, 93, 109, 125, 141, 157, 173, 189, 30, 14, 62, 46, 94, 78, 126, 110, 158, 142, 190, 174, 15, 31, 47, 63, 79, 95, 111, 127, 143, 159, 175, 191, 32, 16, 64, 48, 96, 80, 128, 112, 160, 144, 192, 176]
            k192 = [1, 14, 25, 38, 49, 62, 73, 86, 97, 110, 121, 134, 145, 158, 169, 182, 2, 13, 26, 37, 50, 61, 74, 85, 98, 109, 122, 133, 146, 157, 170, 181, 3, 16, 27, 40, 51, 64, 75, 88, 99, 112, 123, 136, 147, 160, 171, 184, 4, 15, 28, 39, 52, 63, 76, 87, 100, 111, 124, 135, 148, 159, 172, 183, 5, 18, 29, 42, 53, 66, 77, 90, 101, 114, 125, 138, 149, 162, 173, 186, 6, 17, 30, 41, 54, 65, 78, 89, 102, 113, 126, 137, 150, 161, 174, 185, 7, 20, 31, 44, 55, 68, 79, 92, 103, 116, 127, 140, 151, 164, 175, 188, 8, 19, 32, 43, 56, 67, 80, 91, 104, 115, 128, 139, 152, 163, 176, 187, 9, 22, 33, 46, 57, 70, 81, 94, 105, 118, 129, 142, 153, 166, 177, 190, 10, 21, 34, 45, 58, 69, 82, 93, 106, 117, 130, 141, 154, 165, 178, 189, 11, 24, 35, 48, 59, 72, 83, 96, 107, 120, 131, 144, 155, 168, 179, 192, 12, 23, 36, 47, 60, 71, 84, 95, 108, 119, 132, 143, 156, 167, 180, 191]
            p = [(w192[j]-1) for j in range(0, 192)]
            pinv = [(k192[j]-1) for j in range(0, 192)]
        elif self.NCBPS == 288:
            w288 = [1, 17, 33, 49, 65, 81, 97, 113, 129, 145, 161, 177, 193, 209, 225, 241, 257, 273, 18, 34, 2, 66, 82, 50, 114, 130, 98, 162, 178, 146, 210, 226, 194, 258, 274, 242, 35, 3, 19, 83, 51, 67, 131, 99, 115, 179, 147, 163, 227, 195, 211, 275, 243, 259, 4, 20, 36, 52, 68, 84, 100, 116, 132, 148, 164, 180, 196, 212, 228, 244, 260, 276, 21, 37, 5, 69, 85, 53, 117, 133, 101, 165, 181, 149, 213, 229, 197, 261, 277, 245, 38, 6, 22, 86, 54, 70, 134, 102, 118, 182, 150, 166, 230, 198, 214, 278, 246, 262, 7, 23, 39, 55, 71, 87, 103, 119, 135, 151, 167, 183, 199, 215, 231, 247, 263, 279, 24, 40, 8, 72, 88, 56, 120, 136, 104, 168, 184, 152, 216, 232, 200, 264, 280, 248, 41, 9, 25, 89, 57, 73, 137, 105, 121, 185, 153, 169, 233, 201, 217, 281, 249, 265, 10, 26, 42, 58, 74, 90, 106, 122, 138, 154, 170, 186, 202, 218, 234, 250, 266, 282, 27, 43, 11, 75, 91, 59, 123, 139, 107, 171, 187, 155, 219, 235, 203, 267, 283, 251, 44, 12, 28, 92, 60, 76, 140, 108, 124, 188, 156, 172, 236, 204, 220, 284, 252, 268, 13, 29, 45, 61, 77, 93, 109, 125, 141, 157, 173, 189, 205, 221, 237, 253, 269, 285, 30, 46, 14, 78, 94, 62, 126, 142, 110, 174, 190, 158, 222, 238, 206, 270, 286, 254, 47, 15, 31, 95, 63, 79, 143, 111, 127, 191, 159, 175, 239, 207, 223, 287, 255, 271, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256, 272, 288]
            k288 = [1, 21, 38, 55, 75, 92, 109, 129, 146, 163, 183, 200, 217, 237, 254, 271, 2, 19, 39, 56, 73, 93, 110, 127, 147, 164, 181, 201, 218, 235, 255, 272, 3, 20, 37, 57, 74, 91, 111, 128, 145, 165, 182, 199, 219, 236, 253, 273, 4, 24, 41, 58, 78, 95, 112, 132, 149, 166, 186, 203, 220, 240, 257, 274, 5, 22, 42, 59, 76, 96, 113, 130, 150, 167, 184, 204, 221, 238, 258, 275, 6, 23, 40, 60, 77, 94, 114, 131, 148, 168, 185, 202, 222, 239, 256, 276, 7, 27, 44, 61, 81, 98, 115, 135, 152, 169, 189, 206, 223, 243, 260, 277, 8, 25, 45, 62, 79, 99, 116, 133, 153, 170, 187, 207, 224, 241, 261, 278, 9, 26, 43, 63, 80, 97, 117, 134, 151, 171, 188, 205, 225, 242, 259, 279, 10, 30, 47, 64, 84, 101, 118, 138, 155, 172, 192, 209, 226, 246, 263, 280, 11, 28, 48, 65, 82, 102, 119, 136, 156, 173, 190, 210, 227, 244, 264, 281, 12, 29, 46, 66, 83, 100, 120, 137, 154, 174, 191, 208, 228, 245, 262, 282, 13, 33, 50, 67, 87, 104, 121, 141, 158, 175, 195, 212, 229, 249, 266, 283, 14, 31, 51, 68, 85, 105, 122, 139, 159, 176, 193, 213, 230, 247, 267, 284, 15, 32, 49, 69, 86, 103, 123, 140, 157, 177, 194, 211, 231, 248, 265, 285, 16, 36, 53, 70, 90, 107, 124, 144, 161, 178, 198, 215, 232, 252, 269, 286, 17, 34, 54, 71, 88, 108, 125, 142, 162, 179, 196, 216, 233, 250, 270, 287, 18, 35, 52, 72, 89, 106, 126, 143, 160, 180, 197, 214, 234, 251, 268, 288]
            p = [(w288[j]-1) for j in range(0, 288)]
            pinv = [(k288[j]-1) for j in range(0, 288)]

        return np.array(p, dtype = np.int32), np.array(pinv, dtype = np.int32)
    
    def build(self, input_shape):
        assert self._axis < len(input_shape), "Axis does match input shape"
        # init rand sequences during build
        assert input_shape[self._axis] is not None, "Unknown shape at req. dim"
        p, pinv = self._generate_perm()

        multiples = input_shape[-1]//self.NCBPS
        p = np.tile(p, (multiples,))
        pinv = np.tile(pinv, (multiples,))

        for ind in range(0,multiples):
          p[ind*self.NCBPS: (ind+1)*self.NCBPS] += ind*self.NCBPS
          pinv[ind*self.NCBPS: (ind+1)*self.NCBPS] += ind*self.NCBPS
        
        
        self._perm_seq = tf.convert_to_tensor(p, dtype = tf.int32)
        self._perm_seq_inv = tf.convert_to_tensor(pinv, dtype = tf.int32)
        # print("self._perm_seq_inv.shape")
        # print(self._perm_seq_inv.shape)
        # self._perm_seq = tf.tile(tf.convert_to_tensor(p), [input_shape[-1]//self.NCBPS])
        # self._perm_seq_inv = tf.tile(tf.convert_to_tensor(pinv), [input_shape[-1]//self.NCBPS])
        
        
    def call(self, inputs):    

        input_shape = inputs.shape

        # re-init if shape has changed, update perm_seq
        # if inputs.shape[self._axis] != self._perm_seq.shape[0]:
        #     self.build(inputs.shape)

        # print("inputs shape interleaver"); print(inputs.shape)
        if self._inverse:
            x = tf.gather(inputs, self._perm_seq_inv, axis = 3)
            # x = inputs[self._perm_seq_inv]
        else:
            x = tf.gather(inputs, self._perm_seq, axis = 3)
            # x = inputs[self._perm_seq]

        x = tf.ensure_shape(x, input_shape)
        return x

"""# Config Model OFDM params"""

############################################
## Channel configuration
carrier_frequency = 5.9e9 # Hz
delay_spread = 100e-9 # s
cdl_model = "C" # CDL model to use
speed = 10.0 # Speed for evaluation and training [m/s]


############################################
## OFDM waveform configuration
subcarrier_spacing = 312.5e3/2 # Hz
fft_size = 64 # Number of subcarriers forming the resource grid, including the null-subcarrier and the guard bands
num_ofdm_symbols = 20 # Number of OFDM symbols forming the resource grid
dc_null = True # Null the DC subcarrier
num_guard_carriers = [5, 6] # Number of guard carriers on each side
pilot_pattern = "kronecker" # Pilot pattern
pilot_ofdm_symbol_indices = [2, 11] # Index of OFDM symbols carrying pilots
cyclic_prefix_length = 0 # Simulation in frequency domain. This is useless

############################################
## Modulation and coding configuration
num_bits_per_symbol = 6 # 16-QAM
if num_bits_per_symbol == 1: NCBPS  = 48
elif num_bits_per_symbol == 2: NCBPS  = 96
elif num_bits_per_symbol == 4: NCBPS  = 192
elif num_bits_per_symbol == 6: NCBPS  = 288
else: NCBPS  = None
constellation = generate_ieee8211_constellation(mu  = num_bits_per_symbol)

coderate = 0.5 # Coderate for BCC code

############################################
## Neural receiver configuration
num_conv_channels = 128 # Number of convolutional channels for the convolutional layers forming the neural receiver

############################################
## Training configuration
num_training_iterations = 30000 # Number of training iterations
training_batch_size = 64 # Training batch size
model_weights_path = "neural_receiver_weights"+"_R_"+'{:1.2f}'.format(coderate)+"_mu_" + '{:1}'.format(num_bits_per_symbol) # Location to save the neural receiver weights once training is done

############################################
## Evaluation configuration
results_filename = "neural_receiver_results" # Location to save the results


############################################
## Antenna configuration
stream_manager = StreamManagement(np.array([[1]]), # Receiver-transmitter association matrix
                                  1)               # One stream per transmitter
ut_antenna = Antenna(polarization="single",
                     polarization_type="V",
                     antenna_pattern="38.901",
                     carrier_frequency=carrier_frequency)

bs_array = AntennaArray(num_rows=1,
                        num_cols=1,
                        polarization="dual",
                        polarization_type="VH",
                        antenna_pattern="38.901",
                        carrier_frequency=carrier_frequency)

"""# 2. Neural Receiver"""

#!/usr/bin/env python
# coding: utf-8




short_training_symbol=math.sqrt(13/6) * np.array([0, 0, 1+1j, 0, 0, 0, -1-1j, 0, 0, 0,
    1+1j, 0, 0, 0, -1-1j, 0, 0, 0, -1-1j, 0, 0, 0, 1+1j, 0, 0, 0, 0, 0,
    0, 0, -1-1j, 0, 0, 0, -1-1j, 0, 0, 0, 1+1j, 0, 0, 0, 1+1j, 0, 0, 0,
    1+1j, 0, 0, 0, 1+1j, 0,0], dtype=complex)
# print(len(short_training_symbol))

long_training_symbol=np.array([1, 1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1,
    -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 0, 1, -1, -1, 1, 1, -1, 1, -1,
    1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1])
# print(len(long_training_symbol))

pilots=np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, -1, 0, 0, 0, 0, 0])
# print(len(pilots))

pilotpolarity=np.array([1,1,1,1, -1,-1,-1,1, -1,-1,-1,-1, 1,1,-1,1, -1,-1,1,1,
    -1,1,1,-1, 1,1,1,1, 1,1,-1,1,1,1,-1,1, 1,-1,-1,1, 1,1,-1,1,
    -1,-1,-1,1, -1,1,-1,-1, 1,-1,-1,1, 1,1,1,1, -1,-1,1,1,-1,-1,1,-1, 
    1,-1,1,1, -1,-1,-1,1, 1,-1,-1,-1, -1,1,-1,-1, 1,-1,1,1, 1,1,-1,1, 
    -1,1,-1,1,-1,-1,-1,-1, -1,1,-1,1, 1,-1,1,-1, 1,1,1,-1, -1,1,-1,-1,
    -1,1,1,1, -1,-1,-1,-1, -1,-1,-1])
# print(len(pilotpolarity))

def generate_pilot_loc_matrix(N):
    '''
    @param N: symbols additionally added to two long training symbols, and one ...
                data symbol that contains four pilots in subcarriers.
    Generate Pilot location matrix for 802.11p 
    '1' indicates a pilot, '0' indicates data or Null
    Including block and comb type pilots as defined by the standard
    Note: Null subcarriers are also included.
    Returns a matrix of 64 x (N+3)
    '''
    p1 = 7 # subcarrier Pilot location
    p2 = 21 # subcarrier Pilot location
    p3 = 43
    p4 = 57
    # N = 12
    long_pilot_loc = [0 if (ind in range(27,38) or ind == 0) else val for ind, val in enumerate(itertools.repeat(1,64))]
    # len(long_pilot_loc)
    short_pilot_loc = [1 if (ind == p1  or ind == p2 or ind == p3 or ind == p4 ) else val for ind, val in enumerate(itertools.repeat(0,64))]
    # len(short_pilot_loc)
    pilot_matrix_base = list(map(list, zip(long_pilot_loc, long_pilot_loc, short_pilot_loc)))
    pilot_matrix_base = np.array(pilot_matrix_base)
    short_pilots_rep = np.hstack([pilot_matrix_base[:,2].reshape((-1, 1))]*N)
    pilot_matrix_loc = np.concatenate((pilot_matrix_base,short_pilots_rep), 1)
    return pilot_matrix_loc

def generate_pilot_pattern_80211p(num_tx = 1,num_streams_per_tx = 1, num_ofdm_symbols = 3, num_effective_subcarriers = 52, combPilotOnly = False):
    '''
    #num_tx, num_streams_per_tx, num_ofdm_symbols, num_effective_subcar
    '''
    # Generate MASK
    num_ofdm_symbols -=3
    if combPilotOnly:
        num_pilot_symbols = 4*(num_ofdm_symbols -1)
        mask = np.zeros((num_tx,
                 num_streams_per_tx,
                 num_ofdm_symbols -1,
                 num_effective_subcarriers))
        pilots = np.zeros((num_tx,
                 num_streams_per_tx,
                 num_pilot_symbols),
                 dtype=complex)
        pilot_matrix_loc = generate_pilot_loc_matrix(num_ofdm_symbols-3)
    else:
        num_pilot_symbols =52+52 + 4*(num_ofdm_symbols -1)
        mask = np.zeros((num_tx,
                 num_streams_per_tx,
                 num_ofdm_symbols+3,
                 num_effective_subcarriers))
        pilots = np.zeros((num_tx,
                 num_streams_per_tx,
                 num_pilot_symbols +2*4),
                 dtype=complex)
        pilot_matrix_loc = generate_pilot_loc_matrix(num_ofdm_symbols)


    pilot_matrix_loc = np.roll(pilot_matrix_loc[1:],26, axis=0)[0:52].T

    # Generate CombPilots
    ij =2 
    NST = num_effective_subcarriers  #52 + 1 # imprecise Including DC for now
    pilot1 = np.array([1,1,1,-1])
    pilotIndex1 = np.block([4, 18, 33, 47]).tolist()
    # combGrid = np.zeros((num_ofdm_symbols-4,NST),dtype=complex)
    combPilots = np.zeros(num_pilot_symbols -52-52 +2*4,dtype=complex)
    for ii in range(0,num_ofdm_symbols -1 +2):
        inputiFFT1 = np.zeros(NST,dtype = complex)
        inputiFFT1[pilotIndex1] = np.zeros(len(pilotIndex1),dtype = complex)
        ij  = ij%127
        pm = pilotpolarity[ij]
        ij = ij+1
        pilot2 = pm*pilot1
        combPilots[4*ii:4*(ii+1)] = pilot2
        # #Pilots Insertion
        # inputiFFT1[5]=pilot2[0]
        # inputiFFT1[19]=pilot2[1]
        # inputiFFT1[33]=pilot2[2]
        # inputiFFT1[47]=pilot2[3]
        # combGrid[ii, :] = inputiFFT1

    if combPilotOnly:
         pilot_matrix_loc = pilot_matrix_loc[2:][:]
    else:
        pilot_matrix_loc = pilot_matrix_loc[:][:]
    # Block Pilots
    BlockPilot = np.delete(long_training_symbol,26)
         
    for indtx in range(0,num_tx):
        for indstreamtx in range(0,num_streams_per_tx):
            mask[indtx, indstreamtx, :, :] = pilot_matrix_loc
            print(mask.shape)
            print(int(np.sum(mask[0,0])))
            if combPilotOnly:
                pilots[indtx, indstreamtx, :] = combPilots
            else:
                pilots[indtx, indstreamtx, :] = np.block([ BlockPilot, BlockPilot, combPilots])
                print(pilots.shape)
    with tf.device('/cpu:0'):
        pilot_pattern_80211p = PilotPattern(mask = mask, pilots = pilots, trainable=False, normalize=False, dtype=tf.complex64)

    return pilot_pattern_80211p


Nsym = num_ofdm_symbols
pilot_pattern_80211p = generate_pilot_pattern_80211p(num_tx = 1,num_streams_per_tx = 1, num_ofdm_symbols = Nsym, num_effective_subcarriers = 52, combPilotOnly = False)
num_guard_carriers = [6, 5]


resource_grid = ResourceGrid(num_ofdm_symbols = num_ofdm_symbols,
                             fft_size = fft_size,
                             subcarrier_spacing = subcarrier_spacing,
                             num_tx = 1,
                             num_streams_per_tx = 1,
                             cyclic_prefix_length = cyclic_prefix_length,
                             dc_null = dc_null,
                             pilot_pattern = pilot_pattern_80211p,
                             num_guard_carriers = num_guard_carriers) 

print(f"num_data_symbols: {resource_grid.num_data_symbols}")


resource_grid.show()



# Codeword length. It is calculated from the total number of databits carried by the resource grid, and the number of bits transmitted per resource element
n = int(resource_grid.num_data_symbols*num_bits_per_symbol)
# Number of information bits per codeword
k = int(n*coderate) 



class ResidualBlock(Layer):
    r"""
    This Keras layer implements a convolutional residual block made of two convolutional layers with ReLU activation, layer normalization, and a skip connection.
    The number of convolutional channels of the input must match the number of kernel of the convolutional layers ``num_conv_channel`` for the skip connection to work.
    
    Input
    ------
    : [batch size, num time samples, num subcarriers, num_conv_channel], tf.float
        Input of the layer
    
    Output
    -------
    : [batch size, num time samples, num subcarriers, num_conv_channel], tf.float
        Output of the layer
    """
                        
    def build(self, input_shape):
        
        # Layer normalization is done over the last three dimensions: time, frequency, conv 'channels'
        self._layer_norm_1 = LayerNormalization(axis=(-1, -2, -3))
        self._conv_1 = Conv2D(filters=num_conv_channels,
                              kernel_size=[3,3],
                              padding='same',
                              activation=None)
        # Layer normalization is done over the last three dimensions: time, frequency, conv 'channels'
        self._layer_norm_2 = LayerNormalization(axis=(-1, -2, -3))
        self._conv_2 = Conv2D(filters=num_conv_channels,
                              kernel_size=[3,3],
                              padding='same',
                              activation=None)
    
    def call(self, inputs):
        z = self._layer_norm_1(inputs)
        z = relu(z)
        z = self._conv_1(z)
        z = self._layer_norm_2(z)
        z = relu(z)
        z = self._conv_2(z) # [batch size, num time samples, num subcarriers, num_channels]
        # Skip connection
        z = z + inputs
        
        return z

class NeuralReceiver(Layer):
    r"""
    Keras layer implementing a residual convolutional neural receiver.
    
    This neural receiver is fed with the post-DFT received samples, forming a resource grid of size num_of_symbols x fft_size, and computes LLRs on the transmitted coded bits.
    These LLRs can then be fed to an outer decoder to reconstruct the information bits.
    
    As the neural receiver is fed with the entire resource grid, including the guard bands and pilots, it also computes LLRs for these resource elements.
    They must be discarded to only keep the LLRs corresponding to the data-carrying resource elements.
    
    Input
    ------
    y : [batch size, num rx antenna, num ofdm symbols, num subcarriers], tf.complex
        Received post-DFT samples.
    
    no : [batch size], tf.float32
        Noise variance. At training, a different noise variance value is sampled for each batch example.
    
    Output
    -------
    : [batch size, num ofdm symbols, num subcarriers, num_bits_per_symbol]
        LLRs on the transmitted bits.
        LLRs computed for resource elements not carrying data (pilots, guard bands...) must be discarded.
    """
    
    def build(self, input_shape):
        
        # Input convolution
        self._input_conv = Conv2D(filters=num_conv_channels,
                                  kernel_size=[3,3],
                                  padding='same',
                                  activation=None)
        # Residual blocks
        self._res_block_1 = ResidualBlock()
        self._res_block_2 = ResidualBlock()
        self._res_block_3 = ResidualBlock()
        self._res_block_4 = ResidualBlock()
        # Output conv
        self._output_conv = Conv2D(filters=num_bits_per_symbol,
                                   kernel_size=[3,3],
                                   padding='same',
                                   activation=None)
        
    def call(self, inputs):
        y, no = inputs
        
        # Feeding the noise power in log10 scale helps with the performance
        no = log10(no)
        
        # Stacking the real and imaginary components of the different antennas along the 'channel' dimension
        y = tf.transpose(y, [0, 2, 3, 1]) # Putting antenna dimension last
        no = insert_dims(no, 3, 1)
        no = tf.tile(no, [1, y.shape[1], y.shape[2], 1])
        # z : [batch size, num ofdm symbols, num subcarriers, 2*num rx antenna + 1]
        z = tf.concat([tf.math.real(y),
                       tf.math.imag(y),
                       no], axis=-1)
        # Input conv
        z = self._input_conv(z)
        # Residual blocks
        z = self._res_block_1(z)
        z = self._res_block_2(z)
        z = self._res_block_3(z)
        z = self._res_block_4(z)
        # Output conv
        z = self._output_conv(z)
        
        return z


# In[28]:


# ## Transmitter
# binary_source = BinarySource()
# scrambler = IEEE80211Scrambler(seed = 127)
# interleaver = IEEE80211Interleaver(NCBPS = NCBPS, inverse = False)

# encoder = ConvEncoder(rate=k/n, constraint_length=7)


# constellation = generate_ieee8211_constellation(mu  = num_bits_per_symbol)

# mapper = Mapper(constellation_type = "custom", constellation = constellation)
# rg_mapper = ResourceGridMapper(resource_grid)

# ## Channel
# cdl = CDL(cdl_model, delay_spread, carrier_frequency,
#           ut_antenna, bs_array, "uplink", min_speed=speed)
# channel = OFDMChannel(cdl, resource_grid, normalize_channel=True, return_channel=True)

# ## Receiver
# deinterleaver = IEEE80211Interleaver(NCBPS = NCBPS, inverse = True)

# decoder = ViterbiDecoder(encoder)
# descrambler = IEEE80211Scrambler(seed = 127)
# neural_receiver = NeuralReceiver()
# rg_demapper = ResourceGridDemapper(resource_grid, stream_manager) # Used to extract data-carrying resource elements


# In[29]:


# batch_size = 64
# ebno_db = tf.fill([batch_size], 5.0)
# no = ebnodb2no(ebno_db, num_bits_per_symbol, coderate)


# ## Transmitter
# # Generate codewords


# b = binary_source([batch_size, 1, 1, k])
# print("b shape: ", b.shape)
# # Scramble input bits
# b_scr = scrambler(b)
# print("b_scr shape: ", b_scr.shape)
# # Encode FEC input bits
# c_wo_inter = encoder(b_scr)
# print("c_wo_inter shape: ", c_wo_inter.shape)
# # Interleave encoded bits
# c_inter = interleaver(c_wo_inter)
# print("c shape: ", c_inter.shape)
# # Map bits to QAM symbols
# x = mapper(c_inter)
# print("x shape: ", x.shape)
# # Map the QAM symbols to a resource grid
# x_rg = rg_mapper(x)
# print("x_rg shape: ", x_rg.shape)

# ######################################
# ## Channel
# # A batch of new channel realizations is sampled and applied at every inference
# no_ = expand_to_rank(no, tf.rank(x_rg))
# y,_ = channel([x_rg, no_])
# print("y shape: ", y.shape)

# ######################################
# ## Receiver       
# # The neural receover computes LLRs from the frequency domain received symbols and N0
# y = tf.squeeze(y, axis=1)
# llr = neural_receiver([y, no])
# print("llr shape: ", llr.shape)
# # Reshape the input to fit what the resource grid demapper is expected
# llr = insert_dims(llr, 2, 1)
# # Extract data-carrying resource elements. The other LLRs are discarded
# llr = rg_demapper(llr)
# llr = tf.reshape(llr, [batch_size, 1, 1, n])
# print("Post RG-demapper LLRs: ", llr.shape)


# # In[30]:


# bce = tf.nn.sigmoid_cross_entropy_with_logits(c_inter, llr)
# bce = tf.reduce_mean(bce)
# rate = tf.constant(1.0, tf.float32) - bce/tf.math.log(2.)
# print(f"Rate: {rate:.2E} bit")


# # In[34]:


class E2ESystem(Model):
    r"""
    Keras model that implements the end-to-end systems.
    
    As the three considered end-to-end systems (perfect CSI baseline, LS estimation baseline, and neural receiver) share most of
    the link components (transmitter, channel model, outer code...), they are implemented using the same Keras model.

    When instantiating the Keras model, the parameter ``system`` is used to specify the system to setup,
    and the parameter ``training`` is used to specified if the system is instantiated to be trained or to be evaluated.
    The ``training`` parameter is only relevant when the neural 
    
    At each call of this model:
    * A batch of codewords is randomly sampled, modulated, and mapped to resource grids to form the channel inputs
    * A batch of channel realizations is randomly sampled and applied to the channel inputs
    * The receiver is executed on the post-DFT received samples to compute LLRs on the coded bits.
      Which receiver is executed (baseline with perfect CSI knowledge, baseline with LS estimation, or neural receiver) depends
      on the specified ``system`` parameter.
    * If not training, the outer decoder is applied to reconstruct the information bits
    * If training, the BMD rate is estimated over the batch from the LLRs and the transmitted bits
    
    Parameters
    -----------
    system : str
        Specify the receiver to use. Should be one of 'baseline-perfect-csi', 'baseline-ls-estimation' or 'neural-receiver'
    
    training : bool
        Set to `True` if the system is instantiated to be trained. Set to `False` otherwise. Defaults to `False`.
        If the system is instantiated to be trained, the outer encoder and decoder are not instantiated as they are not required for training.
        This significantly reduces the computational complexity of training.
        If training, the bit-metric decoding (BMD) rate is computed from the transmitted bits and the LLRs. The BMD rate is known to be
        an achievable information rate for BICM systems, and therefore training of the neural receiver aims at maximizing this rate.
    
    Input
    ------
    batch_size : int
        Batch size
    
    no : scalar or [batch_size], tf.float
        Noise variance.
        At training, a different noise variance should be sampled for each batch example.
    
    Output
    -------
    If ``training`` is set to `True`, then the output is a single scalar, which is an estimation of the BMD rate computed over the batch. It
    should be used as objective for training.
    If ``training`` is set to `False`, the transmitted information bits and their reconstruction on the receiver side are returned to
    compute the block/bit error rate. 
    """
    
    def __init__(self, system, training=False):
        super().__init__()
        self._system = system
        self._training = training
    
        ######################################
        ## Transmitter
        self._binary_source = BinarySource()
        self._scrambler = IEEE80211Scrambler(seed = 127, batch_size = training_batch_size)
        self._interleaver = IEEE80211Interleaver(NCBPS = NCBPS, inverse = False)

        # To reduce the computational complexity of training, the outer code is not used when training,
        # as it is not required
        if not training:
            self._encoder = ConvEncoder(rate=k/n, constraint_length=7)# ConvEncoder(k, n, 7)

        self._constellation = generate_ieee8211_constellation(mu  = num_bits_per_symbol)
        self._mapper = Mapper(constellation_type = "custom", constellation = self._constellation) #Mapper("qam", num_bits_per_symbol)
        self._rg_mapper = ResourceGridMapper(resource_grid)
        
        ######################################
        ## Channel
        # A 3GPP CDL channel model is used
        cdl = CDL(cdl_model, delay_spread, carrier_frequency,
                  ut_antenna, bs_array, "uplink", min_speed=speed)
        self._channel = OFDMChannel(cdl, resource_grid, normalize_channel=True, return_channel=True)
        
        ######################################
        ## Receiver
        # Three options for the receiver depending on the value of `system`
        if "baseline" in system:
            if system == 'baseline-perfect-csi': # Perfect CSI
                self._removed_null_subc = RemoveNulledSubcarriers(resource_grid)
            elif system == 'baseline-ls-estimation': # LS estimation
                self._ls_est = LSChannelEstimator(resource_grid, interpolation_type="nn")
            # Components required by both baselines
            self._lmmse_equ = LMMSEEqualizer(resource_grid, stream_manager, )
            self._demapper = Demapper(demapping_method = "app",
                                      constellation_type =  "custom",
                                      constellation = constellation )   #Demapper("app", "qam", num_bits_per_symbol)
            self._descrambler = IEEE80211Scrambler(seed = 127, batch_size = training_batch_size)
            self._deinterleaver = IEEE80211Interleaver(NCBPS = NCBPS, inverse = True)
        
        elif system == "neural-receiver":
            # Neural receiver
            self._neural_receiver = NeuralReceiver()
            self._rg_demapper = ResourceGridDemapper(resource_grid, stream_manager) # Used to extract data-carrying resource elements
            # self._descrambler = IEEE80211Scrambler(seed = 127, batch_size = training_batch_size)
        # To reduce the computational complexity of training, the outer code is not used when training,
        # as it is not required
        if not training:

            self._descrambler = IEEE80211Scrambler(seed = 127, batch_size = training_batch_size)
            self._deinterleaver = IEEE80211Interleaver(NCBPS = NCBPS, inverse = True)
            self._decoder = ViterbiDecoder(self._encoder) #LDPC5GDecoder(self._encoder, hard_out=True)
    
    @tf.function
    def call(self, batch_size, ebno_db):
        
        # If `ebno_db` is a scalar, a tensor with shape [batch size] is created as it is what is expected by some layers
        if len(ebno_db.shape) == 0:
            ebno_db = tf.fill([batch_size], ebno_db)
        
        ######################################
        ## Transmitter
        no = ebnodb2no(ebno_db, num_bits_per_symbol, coderate)
        # Outer coding is only performed if not training
        if self._training:
            b = self._binary_source([batch_size, 1, 1, n])
            # b_scr = self._scrambler(b)
            # c = b_scr
            c = b
            
        else:
            
            b = self._binary_source([batch_size, 1, 1, k])

            # With scrambling and interleaving
            b_scr = self._scrambler(b)
            c = self._encoder(b_scr)
            c = self._interleaver(c)
           
            # Without scrambling and interleaving
            # c = self._encoder(b)

        # Modulation
        x = self._mapper(c)
        x_rg = self._rg_mapper(x)
        
        ######################################
        ## Channel
        # A batch of new channel realizations is sampled and applied at every inference
        no_ = expand_to_rank(no, tf.rank(x_rg))
        y,h = self._channel([x_rg, no_])
        
        ######################################
        ## Receiver       
        # Three options for the receiver depending on the value of ``system``
        if "baseline" in self._system:
            if self._system == 'baseline-perfect-csi':
                h_hat = self._removed_null_subc(h) # Extract non-null subcarriers
                err_var = 0.0 # No channel estimation error when perfect CSI knowledge is assumed
            elif self._system == 'baseline-ls-estimation':
                h_hat, err_var = self._ls_est([y, no]) # LS channel estimation with nearest-neighbor
            x_hat, no_eff = self._lmmse_equ([y, h_hat, err_var, no]) # LMMSE equalization
            no_eff_= expand_to_rank(no_eff, tf.rank(x_hat))
            llr = self._demapper([x_hat, no_eff_]) # Demapping
            
        elif self._system == "neural-receiver":
            # The neural receover computes LLRs from the frequency domain received symbols and N0
            y = tf.squeeze(y, axis=1)
            llr = self._neural_receiver([y, no])
            llr = insert_dims(llr, 2, 1) # Reshape the input to fit what the resource grid demapper is expected
            llr = self._rg_demapper(llr) # Extract data-carrying resource elements. The other LLrs are discarded
            llr = tf.reshape(llr, [batch_size, 1, 1, n]) # Reshape the LLRs to fit what the outer decoder is expected

        # Outer coding is not needed if the information rate is returned
        if self._training:
            # Compute and return BMD rate (in bit), which is known to be an achievable
            # information rate for BICM systems.
            # Training aims at maximizing the BMD rate
            bce = tf.nn.sigmoid_cross_entropy_with_logits(c, llr)
            bce = tf.reduce_mean(bce)
            rate = tf.constant(1.0, tf.float32) - bce/tf.math.log(2.)
            return rate
        else:
            # Outer decoding


            llr = self._deinterleaver(llr)
            b_hat_scr = self._decoder(llr)
            b_hat = self._descrambler(b_hat_scr)

            # b_hat = self._decoder(llr)

            
            return b,b_hat # Ground truth and reconstructed information bits returned for BER/BLER computation

"""# 3.0 SNR EbNo value"""

# SNR range for evaluation and training [dB]
ebno_db_min = 0.0
ebno_db_max = 20.0
# Range of SNRs over which the systems are evaluated
ebno_dbs = np.arange(ebno_db_min, # Min SNR for evaluation
                     ebno_db_max, # Max SNR for evaluation
                     1) # Step
# Dictionnary storing the evaluation results
BLER = {}
BER = {}

"""# 3. Baseline"""

model_baseline_perfect_csi = E2ESystem('baseline-perfect-csi')
ber,bler = sim_ber(model_baseline_perfect_csi, ebno_dbs, batch_size=64, num_target_block_errors=100, max_mc_iter=100)
BLER['baseline-perfect-csi'] = bler.numpy(); BER['baseline-perfect-csi'] = ber.numpy()
model_ls_estimation = E2ESystem('baseline-ls-estimation')
ber,bler = sim_ber(model_ls_estimation, ebno_dbs, batch_size=64, num_target_block_errors=100, max_mc_iter=100)
BLER['baseline-ls-estimation'] = bler.numpy(); BER['baseline-ls-estimation'] = ber.numpy()

plt.figure(figsize=(10,6))
# Baseline - Perfect CSI
plt.semilogy(ebno_dbs, BLER['baseline-perfect-csi'], 'o-', c=f'C0', label=f'Baseline - Perfect CSI')    
# Baseline - LS Estimation
plt.semilogy(ebno_dbs, BLER['baseline-ls-estimation'], 'x--', c=f'C1', label=f'Baseline - LS Estimation')
# Neural receiver
plt.semilogy(ebno_dbs, BLER['neural-receiver'], 's-.', c=f'C2', label=f'Neural receiver')
#
plt.xlabel(r"$E_b/N_0$ (dB)")
plt.ylabel("BLER")
plt.grid(which="both")
plt.ylim((1e-4, 1.0))
plt.legend()
plt.tight_layout()

"""# 4. Neural Receiver Training"""

# In[37]:


# The end-to-end system equipped with the neural receiver is instantiated for training.
# When called, it therefore returns the estimated BMD rate
model = E2ESystem('neural-receiver', training=True)

# Sampling a batch of SNRs
ebno_db = tf.random.uniform(shape=[], minval=ebno_db_min, maxval=ebno_db_max)
# Forward pass
with tf.GradientTape() as tape:
    rate = model(training_batch_size, ebno_db)
    # Tensorflow optimizers only know how to minimize loss function.
    # Therefore, a loss function is defined as the additive inverse of the BMD rate
    loss = -rate

# In[38]:


optimizer = tf.keras.optimizers.Adam()

# Computing and applying gradients        
weights = model.trainable_weights
grads = tape.gradient(loss, weights)
optimizer.apply_gradients(zip(grads, weights))

# In[39]:


model_nn_receiver = E2ESystem('neural-receiver', training=True)

optimizer = tf.keras.optimizers.Adam()

for i in range(num_training_iterations):
    # Sampling a batch of SNRs
    ebno_db = tf.random.uniform(shape=[], minval=ebno_db_min, maxval=ebno_db_max)
    # Forward pass
    with tf.GradientTape() as tape:
        rate = model_nn_receiver(training_batch_size, ebno_db)
        # Tensorflow optimizers only know how to minimize loss function.
        # Therefore, a loss function is defined as the additive inverse of the BMD rate
        loss = -rate
    # Computing and applying gradients        
    weights = model_nn_receiver.trainable_weights
    grads = tape.gradient(loss, weights)
    optimizer.apply_gradients(zip(grads, weights))
    # Periodically printing the progress
    if i % 100 == 0:
        print('Iteration {}/{}  Rate: {:.4f} bit'.format(i, num_training_iterations, rate.numpy()), end='\r')

# Save the weights in a file
weights = model_nn_receiver.get_weights()
with open(model_weights_path, 'wb') as f:
    pickle.dump(weights, f)


# In[40]:


model_nn_receiver_trained = E2ESystem('neural-receiver')

# Run one inference to build the layers and loading the weights
model_nn_receiver_trained(1, tf.constant(10.0, tf.float32))
with open(model_weights_path, 'rb') as f:
    weights = pickle.load(f)
model_nn_receiver_trained.set_weights(weights)

# Evaluations
_,bler = sim_ber(model_nn_receiver_trained, ebno_dbs, batch_size=64, num_target_block_errors=100, max_mc_iter=100)
BLER['neural-receiver'] = bler.numpy()


# In[41]:


plt.figure(figsize=(10,6))
# Baseline - Perfect CSI
plt.semilogy(ebno_dbs, BLER['baseline-perfect-csi'], 'o-', c=f'C0', label=f'Baseline - Perfect CSI')    
# Baseline - LS Estimation
plt.semilogy(ebno_dbs, BLER['baseline-ls-estimation'], 'x--', c=f'C1', label=f'Baseline - LS Estimation')
# Neural receiver
plt.semilogy(ebno_dbs, BLER['neural-receiver'], 's-.', c=f'C2', label=f'Neural receiver')
#
plt.xlabel(r"$E_b/N_0$ (dB)")
plt.ylabel("BLER")
plt.grid(which="both")
plt.ylim((1e-4, 1.0))
plt.legend()
plt.tight_layout()


# In[42]:


# pre_computed_results = "{'baseline-perfect-csi': [1.0, 1.0, 1.0, 1.0, 1.0, 0.9916930379746836, 0.5367080479452054, 0.0285078125, 0.0017890625, 0.0006171875, 0.0002265625, 9.375e-05, 2.34375e-05, 7.8125e-06, 1.5625e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'baseline-ls-estimation': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9998022151898734, 0.9199448529411764, 0.25374190938511326, 0.0110234375, 0.002078125, 0.0008359375, 0.0004375, 0.000171875, 9.375e-05, 4.6875e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'neural-receiver': [1.0, 1.0, 1.0, 1.0, 1.0, 0.9984177215189873, 0.7505952380952381, 0.10016025641025642, 0.00740625, 0.0021640625, 0.000984375, 0.0003671875, 0.000203125, 0.0001484375, 3.125e-05, 2.34375e-05, 7.8125e-06, 7.8125e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}"
# BLER = eval(pre_computed_results)


# In[ ]:

# |BLER

resource_grid.num_data_symbols

"""## References <a class="anchor" id="References"></a>

[1] M. Honkala, D. Korpi and J. M. J. Huttunen, "DeepRx: Fully Convolutional Deep Learning Receiver," in IEEE Transactions on Wireless Communications, vol. 20, no. 6, pp. 3925-3940, June 2021, doi: 10.1109/TWC.2021.3054520.

[2] F. Ait Aoudia and J. Hoydis, "End-to-end Learning for OFDM: From Neural Receivers to Pilotless Communication," in IEEE Transactions on Wireless Communications, doi: 10.1109/TWC.2021.3101364.

[3] Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun, "Deep Residual Learning for Image Recognition", Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2016, pp. 770-778

[4] G. Böcherer, "Achievable Rates for Probabilistic Shaping", arXiv:1707.01134, 2017.
"""

# llr.shape

# b_scr.shape

# c_wo_inter.shape

